import type { TodoItem } from './types';

export const ultraPlan2TodoList: TodoItem[] = [
  {
    id: 1,
    title: 'Auth-Domain + lokalem User',
    status: 'completed',
    objective: 'User-Identitaet (Name, Rolle) lokal verwalten und im Audit-Log nutzen.',
    deliverable: 'src/domain/auth.ts mit loadUser/saveUser',
  },
  {
    id: 2,
    title: 'Audit-Actor dynamisch',
    status: 'completed',
    objective: 'Audit-Events tragen den echten Displaynamen und die Rolle des Nutzers.',
    deliverable: 'App.tsx nutzt User-State fuer Audit-Actor',
  },
  {
    id: 3,
    title: 'PromptContract-Domain',
    status: 'completed',
    objective: 'Typisierte Prompt-Vertraege pro Workflow-Schritt modellieren.',
    deliverable: 'src/domain/promptContract.ts',
  },
  {
    id: 4,
    title: 'Guardrail-Domain',
    status: 'completed',
    objective: 'Aktive Sicherheitsregeln mit Schweregrad und Geltungsbereich modellieren.',
    deliverable: 'src/domain/guardrails.ts',
  },
  {
    id: 5,
    title: 'CRICheck-Domain + Score',
    status: 'completed',
    objective: 'Clinical Readiness Index berechnen und sichtbar machen.',
    deliverable: 'src/domain/cri.ts mit calcCRIScore',
  },
  {
    id: 6,
    title: 'OpenGates-Domain',
    status: 'completed',
    objective: 'Offene Entscheidungen als typisierte Domainquelle ablegen.',
    deliverable: 'src/domain/openGates.ts',
  },
  {
    id: 7,
    title: 'WorkflowStep-Completion',
    status: 'completed',
    objective: 'Steps koennen als completed markiert werden; State wird persistiert.',
    deliverable: 'Completed-Badge + localStorage fuer Step-Zustände',
  },
  {
    id: 8,
    title: 'Fortschrittsbalken Workflow',
    status: 'completed',
    objective: 'Visueller Progress-Indicator zeigt absolvierten Workflow-Anteil.',
    deliverable: 'Progress-Bar im First-Workflow-Slice',
  },
  {
    id: 9,
    title: 'PromptContract + Guardrails im Panel',
    status: 'completed',
    objective: 'Detail-Panel zeigt Vertrag und aktive Regeln fuer den gewahlten Schritt.',
    deliverable: 'Erweitertes Workflow-Detail mit Contract + Guardrail-Liste',
  },
  {
    id: 10,
    title: 'Explainability-Checkliste',
    status: 'completed',
    objective: 'Interaktive Checkliste fuer Schritt 3 mit Audit-Hook bei Abschluss.',
    deliverable: 'ChecklistPanel-Komponente fuer Explainability Review',
  },
  {
    id: 11,
    title: 'CRI-Score-Widget',
    status: 'completed',
    objective: 'Live-Score aus CRIChecks in der UI mit Farbe und Zahl anzeigen.',
    deliverable: 'CRI-Widget-Sektion in der App',
  },
  {
    id: 12,
    title: 'Dark-Mode-Toggle',
    status: 'completed',
    objective: 'Helligkeitsumschalter mit localStorage-Persistenz.',
    deliverable: 'Dark-Mode-Button in der Topbar',
  },
  {
    id: 13,
    title: 'Keyboard-Navigation Workflow',
    status: 'completed',
    objective: 'Pfeiltasten (←/→) wechseln den aktiven Workflow-Schritt.',
    deliverable: 'keydown-Handler auf Workflow-Container',
  },
  {
    id: 14,
    title: 'ErrorBoundary-Komponente',
    status: 'completed',
    objective: 'React-ErrorBoundary faengt Render-Fehler ab und zeigt sicheren Fallback.',
    deliverable: 'src/ErrorBoundary.tsx + Integration in main.tsx',
  },
  {
    id: 15,
    title: 'Ultraplan-Filter nach Status',
    status: 'completed',
    objective: 'Nutzer kann Ultraplan nach "alle / aktiv / erledigt" filtern.',
    deliverable: 'Filter-Buttons mit React-State',
  },
  {
    id: 16,
    title: 'Evidence-Preview',
    status: 'completed',
    objective: 'Letzten exportierten Bundle als kompakte Zusammenfassung in der UI zeigen.',
    deliverable: 'Evidence-Preview-Panel in der App',
  },
  {
    id: 17,
    title: 'Ultraplan-2-Datensatz',
    status: 'completed',
    objective: 'Zweiten 20er-Plan als zentrale Domain-Quelle anlegen.',
    deliverable: 'src/domain/ultraplan2.ts',
  },
  {
    id: 18,
    title: 'Ultraplan-2-UI-Sektion',
    status: 'completed',
    objective: 'Zweiten Plan in der App als eigene Sektion sichtbar machen.',
    deliverable: 'Neue Ultraplan-2-Sektion in App.tsx',
  },
  {
    id: 19,
    title: 'Tests fuer neue Features',
    status: 'completed',
    objective: 'CRI-Score, Guardrails, AuthDomain, OpenGates per Unit-Test absichern.',
    deliverable: 'Erweiterte App.test.tsx',
  },
  {
    id: 20,
    title: 'CI gruen + Run-Log',
    status: 'completed',
    objective: 'Alle 20 Punkte abgeschlossen, CI-Gate gruen, Run-Log aktualisiert.',
    deliverable: 'Gruener CI + Run-Log-Eintrag',
  },
];
